### PR TITLE
Add Ubuntu 24.04 support

### PR DESCRIPTION
**Pull request by sbancal**
Since Ubuntu 24.04 doesn't allow `pip3 --user` commands, we have to create a virtualenv dedicated to _ENACrestic_ and link the executable, *.desktop and icon to the user's context so that it can be run smoothly.

### CODE REVIEW

**Comment by nicdub** [comment]
Hi Sam!
While trying to test your PR I had to install poetry which uses `pipx`, could that tool simplify the installation of ENACrestic too?

**Comment by sbancal** [comment]
🤔 Good question ... haven't tested.
I'll try and let you know

**Comment by sbancal** [comment]
This would mean the end of support for Ubuntu 18.04 ... since _pipx_ requires at least Python 3.8.
But this seems to be ok, since U18.04 has ended to be supported in 2023.

**Review by nicdub — APPROVED** [review]
Oh good point, your PR works with all versions ;) LGTM 👍

**Comment by sbancal** [comment]
If you don't mind, I'd prefer to check the `pipx` way to install before merging. I think it's a good scenario if it simplifies the setup on recent/supported OS.

I think it's ok to drop support for 18.04 since Canonical doesn't support it either.

**Comment by sbancal** [comment]
@nicdub `pipx` makes it even easier for the end user, so I switched the doc to it.

Support for _18.04_ has been discontinued.

**Review by nicdub — APPROVED** [review]
Cool, LGTM 👍

**Pull request merged**
